### ISSUE TITLE
Update function list

### ISSUE THREAD

**Issue by stefangabos** [redelschaap/PHP-Version-Checker#1]
Can you please update functions.xml to also include functions from PHP 5.4 onwards?
I'd be happy to help if you just tell me how you did it in the first place :)
Thanks!

**Comment by stefangabos** [comment]
Nevermind - I just noticed the phpFunctionsCrawler.class.php

**Comment by redelschaap** [comment]
Yes, calling 

```
$phpCrawler = new phpFunctionsCrawler();
$phpCrawler->scrapeFunctionIndex();
$phpCrawler->scrapeFunctions();
$phpCrawler->saveToXMLFile('functions/functions.xml');
```

will update the XML file for you
